### ISSUE TITLE
Content is not being piped into the www dir

### ISSUE THREAD

**Issue by justinmchase** [SamVerschueren/gulp-cordova-create#12]
``` js
var gulp = require('gulp')
var create = require('gulp-cordova-create')
gulp.task('dist', ['clean', 'build'], () => {
  return gulp
    .src('build/app')
    .pipe(create())
})
```

I have a single html and js file in my `build/app`. When I look in `.cordova/www` it is full of the default files, my files are not showing up.

**Comment by SamVerschueren** [comment]
Does your directory structure look something like this?

```
- build
   |--- dist
       |--- index.html
       |--- main.js
- gulpfile.js
```

**Comment by justinmchase** [comment]
No, sorry it was more like:

```
- build
  |--- app
      |--- index.html
      |--- index.js
- gulpfile.js
```

**Comment by justinmchase** [comment]
I actually have a `lib/app` with the code in it, which I am using gulp-babel to transpile into the `build/app` dir. The idea is that eventually I would run the `gulp dist` command and it would go all the way to the android app. But when developing locally I'll just serve it up with express.

**Comment by SamVerschueren** [comment]
I can reproduce. It seems that they did some breaking change from `cordova-lib@6.2.0` to `cordova-lib@6.3.0`.

**Comment by SamVerschueren** [comment]
Release `gulp-cordova-create@1.3.1` with a "fix" for this. I removed the semver range `^6.0.0` to `6.2.0`.

Might have to do this in other `gulp-cordova-*` libs as well if they did other breaking changes. So if you encounter things that aren't working, feel free to file a PR with that change and I'll merge and release.

**Comment by SamVerschueren** [comment]
And thanks for reporting!
