### ISSUE TITLE
Wont build with npm 3.3.12+ 

### ISSUE THREAD

**Issue by pursual** [SamVerschueren/gulp-cordova-create#9]
npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! path /home/ec2-user/mobile-app-dashboard/node_modules/gulp-cordova-create/node_modules/npm/node_modules/rimraf/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ec2-user/mobile-app-dashboard/node_modules/gulp-cordova-create/node_modules/npm/node_modules/rimraf/bin.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/mobile-app-dashboard/npm-debug.log

**Comment by SamVerschueren** [comment]
Can you sure your gulpfile?

**Comment by pursual** [comment]
Yes, but this is on "npm install" before any gulp actions. I believe it is because npm no longer "nests" modules, and this is looking for a nested file.

**Comment by SamVerschueren** [comment]
Can you remove your node_modules directory and run npm install again?

Is it possible that you've upgraded npm without reinstalling the dependencies?

**Comment by pursual** [comment]
I have tried that many times. I have 6 modules all with the same error. Also cleared npm cache and updated npm from 3.3.12 to 3.4. This is on AWS linux, not sure that matters.

**Comment by pursual** [comment]
npm debug log: http://ec2-54-236-86-159.compute-1.amazonaws.com:3000/npm-debug.log

**Comment by pursual** [comment]
Confirmed same problem on osx. Someone reported issue at npm, with gulp-cordova-create as an example:  https://github.com/npm/npm/issues/10234

**Comment by SamVerschueren** [comment]
@robertbaker any thoughts on this?

**Comment by pursual** [comment]
Confirmed that gulp-cordova-create builds correctly in npm 3.3.10. Not sure if it can be improved to work with later versions or if its simply an npm problem.

**Comment by SamVerschueren** [comment]
That's why it's working for me, running on `3.3.10`. Guess we'll just have to wait untill `cordova-lib` upgrades to a later version.

**Comment by ghost** [comment]
@SamVerschueren I was able to build using NPM@3.4.1 using the dependency changes I did PR's for. You can version and tag the plugins and have @pursual try them with the newer dependencies.

I know that npm@3.5.0 is due out soon that should fix a lot of the problems.

**Comment by SamVerschueren** [comment]
Alright, thanks for clarifying! Should better get those updates out then :).

**Comment by SamVerschueren** [comment]
@pursual Reinstall `gulp-cordova-create` and you should be good to go (probably). @robertbaker upgraded all my dependencies a while ago but I didn't had the time to release the changes, didn't knew it was fixing such an important thing to be honest :).

If other libs are failing as well, please create a new issue and contact me back. Will release the other libs this weekend.

**Comment by pursual** [comment]
Confirmed that the new npm 3.4.1 still cant build 1.1.1  
Version 1.2.0 is working. Thanks!
